pull in updates from Trevor McDonell for testing
Both fold bugs persist on my destop. That is, flots crash and Doubles
have the wrong value

$ stack build && stack exec foldSegBug
945.0
Scalar Z [3446.0]
foldSegBug:
*** Internal error in package accelerate ***
*** Please submit a bug report at
https://github.com/AccelerateHS/accelerate/issues
src/Data/Array/Accelerate/LLVM/PTX/State.hs:58:9: (unhandled): CUDA
Exception: an illegal memory access was encountered